"""Build the single-header distribution of kalman-c.

Usage: python scripts/amalgamate.py <out-dir> [--arduino]

Writes <out-dir>/kalman_c.h. Include it anywhere; in exactly one C file,
define KALMAN_C_IMPLEMENTATION before including it to compile the library.
Configuration macros (KF_USE_DOUBLE, KF_MAX_STATE, KF_MAX_MEAS, KF_SPECIALIZE)
must be the same in every file that includes it.

With --arduino, also writes <out-dir>/kalman-c-arduino-<version>.zip, an
Arduino library (library.properties, src/kalman_c.h, src/kalman_c.c) that the
Arduino IDE installs with "Sketch > Include Library > Add .ZIP Library".
"""
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Public headers in dependency order, then the implementation in dependency order.
PUBLIC = ["kf_config.h", "kf_types.h", "kf_linalg.h", "kf_linear.h", "kf_ekf.h", "kf_ukf.h",
          "kf_sqrt.h", "kf_fixed.h"]
IMPL = ["kf_internal.h", "kf_linalg_impl.h", "kf_linalg.c", "kf_linear.c", "kf_ekf.c", "kf_ukf.c",
        "kf_sqrt.c", "kf_fixed.c"]
LOCAL_INCLUDE = re.compile(r'^\s*#include\s+"[^"]+"\s*$', re.M)
SYSTEM_INCLUDE = re.compile(r"^\s*#include\s+<([^>]+)>\s*$", re.M)
GUARD = re.compile(r"\A(?P<pre>(?:\s*/\*.*?\*/)?\s*)#ifndef (\w+)\n#define \2\n(?P<body>.*)#endif\s*\Z",
                   re.S)


def body_of(path):
    """File contents without its include guard and without #include lines."""
    text = open(path).read()
    m = GUARD.match(text)
    if m:
        text = m.group("pre") + m.group("body")
    system = SYSTEM_INCLUDE.findall(text)
    text = SYSTEM_INCLUDE.sub("", LOCAL_INCLUDE.sub("", text))
    return re.sub(r"\n{3,}", "\n\n", text).strip() + "\n", system


def version():
    config = open(os.path.join(ROOT, "include", "kalman", "kf_config.h")).read()
    return re.search(r'#define KALMAN_C_VERSION "([\d.]+)"', config).group(1)


def amalgamate():
    ver = version()
    public, impl, system = [], [], []
    for name in PUBLIC:
        text, inc = body_of(os.path.join(ROOT, "include", "kalman", name))
        public.append(f"/* ---- {name} ---- */\n\n{text}")
        system += inc
    for name in IMPL:
        text, inc = body_of(os.path.join(ROOT, "src", name))
        impl.append(f"/* ---- {name} ---- */\n\n{text}")
        system += inc
    includes = "\n".join(f"#include <{h}>" for h in sorted(set(system)))
    license_text = open(os.path.join(ROOT, "LICENSE")).read().strip()
    license_comment = "\n".join((" * " + line).rstrip() for line in license_text.splitlines())
    return f"""/*
 * kalman-c {ver}: single-header distribution.
 * Generated by scripts/amalgamate.py; do not edit. Source: include/ and src/.
 *
 * Include this header wherever you use the library. In exactly one C file,
 * define KALMAN_C_IMPLEMENTATION before including it:
 *
 *     #define KALMAN_C_IMPLEMENTATION
 *     #include "kalman_c.h"
 *
 * Configuration macros (KF_USE_DOUBLE, KF_MAX_STATE, KF_MAX_MEAS,
 * KF_SPECIALIZE) must be the same everywhere the header is included.
 *
{license_comment}
 */
#ifndef KALMAN_C_H
#define KALMAN_C_H

{includes}

{chr(10).join(public)}
#endif /* KALMAN_C_H */

#ifdef KALMAN_C_IMPLEMENTATION
#ifndef KALMAN_C_IMPLEMENTATION_DONE
#define KALMAN_C_IMPLEMENTATION_DONE

{chr(10).join(impl)}
#endif /* KALMAN_C_IMPLEMENTATION_DONE */
#endif /* KALMAN_C_IMPLEMENTATION */
"""


def arduino_zip(out_dir, header):
    ver = version()
    props = f"""name=kalman-c
version={ver}
author=joslo2345
maintainer=joslo2345
sentence=Embedded-friendly Kalman filters (KF, EKF, UKF) with no dynamic allocation.
paragraph=Joseph-form covariance updates, Cholesky solves, float or double, and errors that leave the filter state unchanged.
category=Data Processing
url=https://github.com/joslo2345/kalman-c
architectures=*
includes=kalman_c.h
"""
    impl_c = '/* Compiles the kalman-c implementation for Arduino. */\n' \
             '#define KALMAN_C_IMPLEMENTATION\n#include "kalman_c.h"\n'
    path = os.path.join(out_dir, f"kalman-c-arduino-{ver}.zip")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("kalman-c/library.properties", props)
        z.writestr("kalman-c/src/kalman_c.h", header)
        z.writestr("kalman-c/src/kalman_c.c", impl_c)
        z.write(os.path.join(ROOT, "LICENSE"), "kalman-c/LICENSE")
    return path


def main():
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)
    header = amalgamate()
    path = os.path.join(out_dir, "kalman_c.h")
    with open(path, "w", newline="\n") as f:
        f.write(header)
    print(f"wrote {path}")
    if "--arduino" in sys.argv[2:]:
        print(f"wrote {arduino_zip(out_dir, header)}")


if __name__ == "__main__":
    main()
