"""Write the first STEPS steps of a scenario as a C header for the firmware.

Usage: python scripts/gen_fw_data.py tests/vectors/S2.txt out/fw_data.h [steps] [frac_bits]

Float values are rounded decimal -> double -> float, exactly as the desktop
loader does, and written as hex float literals so the compiler cannot round
them differently. The same data is also written in the fixed-point Q format
with frac_bits fractional bits (default 20), rounded to nearest with ties away
from zero, as kf_fx_from_double() does, as <id>_fx_* int32 arrays.
"""
import struct
import sys

src, dst = sys.argv[1], sys.argv[2]
steps = int(sys.argv[3]) if len(sys.argv) > 3 else 1000
frac = int(sys.argv[4]) if len(sys.argv) > 4 else 20


def to_f32(v):
    return struct.unpack("<f", struct.pack("<f", float(v)))[0]


def lit(v):
    return float.hex(to_f32(v)) + "f"


def fx(v):
    scaled = float(v) * (1 << frac)
    r = int(scaled + 0.5) if scaled >= 0 else -int(-scaled + 0.5)
    if not -(1 << 31) <= r < (1 << 31):
        sys.exit(f"value {v} does not fit Q{31 - frac}.{frac}")
    return f"{r}" if r != -(1 << 31) else "INT32_MIN"


header, rows = {}, []
with open(src) as f:
    for line in f:
        key, _, rest = line.partition(" ")
        if key == "data":
            break
        header[key] = rest.split()
    n, m = int(header["n"][0]), int(header["m"][0])
    for line in f:
        if len(rows) == steps:
            break
        vals = line.split()
        rows.append(vals[2 + n:2 + n + m])

sid = header["id"][0].lower()
out = [f"/* Generated by scripts/gen_fw_data.py from {src.split('/')[-1]}: first {steps} steps. */",
       "#ifndef FW_DATA_H", "#define FW_DATA_H", "", "#include <stdint.h>", "",
       f"#define {sid.upper()}_N {n}", f"#define {sid.upper()}_M {m}",
       f"#define {sid.upper()}_STEPS {steps}", ""]
for key in ("F", "H", "Q", "R", "x0", "P0"):
    vals = ", ".join(lit(v) for v in header[key])
    out.append(f"static const float {sid}_{key}[{len(header[key])}] = {{{vals}}};")
out.append(f"static const float {sid}_z[{steps}][{m}] = {{")
out += ["    {" + ", ".join(lit(v) for v in r) + "}," for r in rows]
out += ["};", "", f"/* The same data in Q{31 - frac}.{frac} fixed point. */", f"#define {sid.upper()}_FX_FRAC {frac}"]
for key in ("F", "H", "Q", "R", "x0", "P0"):
    vals = ", ".join(fx(v) for v in header[key])
    out.append(f"static const int32_t {sid}_fx_{key}[{len(header[key])}] = {{{vals}}};")
out.append(f"static const int32_t {sid}_fx_z[{steps}][{m}] = {{")
out += ["    {" + ", ".join(fx(v) for v in r) + "}," for r in rows]
out += ["};", "", "#endif", ""]
open(dst, "w").write("\n".join(out))
