"""Write the first STEPS steps of a scenario as a C header for the firmware.

Usage: python scripts/gen_fw_data.py tests/vectors/S2.txt out/fw_data.h [steps]

Values are rounded decimal -> double -> float, exactly as the desktop loader
does, and written as hex float literals so the compiler cannot round them
differently.
"""
import struct
import sys

src, dst = sys.argv[1], sys.argv[2]
steps = int(sys.argv[3]) if len(sys.argv) > 3 else 1000


def to_f32(v):
    return struct.unpack("<f", struct.pack("<f", float(v)))[0]


def lit(v):
    return float.hex(to_f32(v)) + "f"


header, rows = {}, []
with open(src) as f:
    for line in f:
        key, _, rest = line.partition(" ")
        if key == "data":
            break
        header[key] = rest.split()
    n, m = int(header["n"][0]), int(header["m"][0])
    for line in f:
        if len(rows) == steps:
            break
        vals = line.split()
        rows.append(vals[2 + n:2 + n + m])

sid = header["id"][0].lower()
out = [f"/* Generated by scripts/gen_fw_data.py from {src.split('/')[-1]}: first {steps} steps. */",
       "#ifndef FW_DATA_H", "#define FW_DATA_H", "",
       f"#define {sid.upper()}_N {n}", f"#define {sid.upper()}_M {m}",
       f"#define {sid.upper()}_STEPS {steps}", ""]
for key in ("F", "H", "Q", "R", "x0", "P0"):
    vals = ", ".join(lit(v) for v in header[key])
    out.append(f"static const float {sid}_{key}[{len(header[key])}] = {{{vals}}};")
out.append(f"static const float {sid}_z[{steps}][{m}] = {{")
out += ["    {" + ", ".join(lit(v) for v in r) + "}," for r in rows]
out += ["};", "", "#endif", ""]
open(dst, "w").write("\n".join(out))
