"""Build comparison.md: the CI comparison report from the guide's Step 7.

Usage: python scripts/make_comparison_report.py <ctest -V log> [regression.md] > comparison.md

Collects every "[report] ..." line the comparison tests print (stability
against the baselines, NIS/NEES consistency, square-root accuracy,
fixed-point tracking) and the instruction-count regression table from
scripts/check_regression.py.
"""
import os
import re
import subprocess
import sys

log_path = sys.argv[1]
regression_path = sys.argv[2] if len(sys.argv) > 2 else None

reports = []
for line in open(log_path, errors="replace"):
    m = re.search(r"\[report\] (.*)$", line.rstrip())
    if m and m.group(1) not in reports:
        reports.append(m.group(1))

def git(*args):
    try:
        return subprocess.run(["git", *args], check=True, capture_output=True, text=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"

commit = os.environ.get("GITHUB_SHA", git("rev-parse", "HEAD"))[:7]
print("# kalman-c comparison report\n")
print(f"Commit `{commit}`. Generated by `scripts/make_comparison_report.py` in CI.\n")

print("## Speed regression check\n")
if regression_path and os.path.exists(regression_path):
    print(open(regression_path).read())
else:
    print("_The regression check did not produce a table (see the job log)._\n")

groups = {}
for r in reports:
    key = r.split(" ")[0]
    groups.setdefault(key, []).append(r)
titles = {"stability": "Numerical stability against the baselines",
          "consistency": "NIS / NEES consistency (500 Monte Carlo trials)",
          "sqrt": "Square-root (UD) covariance accuracy",
          "fixed-point": "Fixed-point tracking of the float filter"}
print("## Comparison reports from the test suite\n")
if not reports:
    print("_No [report] lines found in the test log._")
for key, lines in groups.items():
    print(f"### {titles.get(key, key)}\n")
    for line in lines:
        print(f"- {line}")
    print()
